archive_folder:
archive_fail_folder:

dim_table_config:
  dim_customer:
    transform_module:
    sql_table_name: dim_customer_info
    schema: sale

  dim_channel:
    transform_module:
    sql_table_name: dim_channel
    schema: sale

  dim_product:
    transform_module:
    sql_table_name: dim_product
    schema: sale

  dim_saleperson:
    transform_module:
    sql_table_name: dim_saleperson
    schema: sale

fact_table_config:
  fact_order_sale:
    transform_module:
    sql_table_name: fact_order_sale
    schema: sale
